In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
dataset = pd.read_csv("Hargovind - Sheet2.csv")

In [27]:
dataset

,Bill Date,Tran Type,Bill Prefix,Bill No,Customer Code,Customer Name,Sales Man Code,Item Promo Code,Bill Promo Code,StockNo,...,Qty,Value,Addons,Deduction,Tax Perc.,Tax,Item - Discount,Bill - Discount,Total - Discount,Old Bill Ref.
0,01/02/2020,Return,W49R19,4.0,9.198114e+11,Pradeep Sharma,RH07117,HO-30-W49-TRS-190120,NaN,890757867060919020,...,-1.0,(1959.00),0.0,(0.30),12.0,(209.93),(839.70),0.0,-839.7,W49S19-107
2,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792245642219090,...,1.0,2999.00,0.0,0.00,12.0,321.32,0.00,0.0,0.0,
3,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792161957619020,...,1.0,2799.00,0.0,0.00,12.0,299.89,0.00,0.0,0.0,
4,01/02/2020,Sales,W49S19,112.0,9.198101e+11,Mr. Vijay Gulati,RH07117,NaN,NaN,890792164244419100,...,1.0,2599.00,0.0,0.00,12.0,278.46,0.00,0.0,0.0,
5,01/02/2020,Sales,W49S19,113.0,9.198101e+11,Mrs. Shashi Mrs,RH06987,HO-30-TRS-270120,NaN,890766615475218080,...,1.0,1539.00,0.0,0.30,12.0,164.93,659.70,0.0,659.7,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,01/12/2020,Sales,W49S20,693.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890511344452420010,...,1.0,2399.00,0.0,0.00,12.0,257.04,0.00,0.0,0.0,
153,01/12/2020,Sales,W49S20,694.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890792238829719070,...,1.0,6999.00,0.0,0.00,12.0,749.89,0.00,0.0,0.0,
154,01/12/2020,Sales,W49S20,695.0,9.199000e+11,Mr Tarun Varma,RH00745,NaN,NaN,890725301064518110,...,1.0,1350.00,0.0,0.00,18.0,205.93,0.00,0.0,0.0,
155,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,Q008210304,...,2.2,3505.00,0.4,0.00,5.0,166.89,0.00,0.0,0.0,
156,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,890511310051220020,...,1.0,2899.00,0.0,0.00,12.0,310.61,0.00,0.0,0.0,

In [21]:
index_to_drop = dataset.index[dataset["Bill Date"].str.contains("Sub")].to_list()

In [22]:
for i in index_to_drop:
    dataset = dataset.drop(i)

In [23]:
dataset

,Bill Date,Tran Type,Bill Prefix,Bill No,Customer Code,Customer Name,Sales Man Code,Item Promo Code,Bill Promo Code,StockNo,...,Qty,Value,Addons,Deduction,Tax Perc.,Tax,Item - Discount,Bill - Discount,Total - Discount,Old Bill Ref.
0,01/02/2020,Return,W49R19,4.0,9.198114e+11,Pradeep Sharma,RH07117,HO-30-W49-TRS-190120,NaN,890757867060919020,...,-1.0,(1959.00),0.0,(0.30),12.0,(209.93),(839.70),0.0,-839.7,W49S19-107
2,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792245642219090,...,1.0,2999.00,0.0,0.00,12.0,321.32,0.00,0.0,0.0,
3,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792161957619020,...,1.0,2799.00,0.0,0.00,12.0,299.89,0.00,0.0,0.0,
4,01/02/2020,Sales,W49S19,112.0,9.198101e+11,Mr. Vijay Gulati,RH07117,NaN,NaN,890792164244419100,...,1.0,2599.00,0.0,0.00,12.0,278.46,0.00,0.0,0.0,
5,01/02/2020,Sales,W49S19,113.0,9.198101e+11,Mrs. Shashi Mrs,RH06987,HO-30-TRS-270120,NaN,890766615475218080,...,1.0,1539.00,0.0,0.30,12.0,164.93,659.70,0.0,659.7,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,01/12/2020,Sales,W49S20,693.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890511344452420010,...,1.0,2399.00,0.0,0.00,12.0,257.04,0.00,0.0,0.0,
153,01/12/2020,Sales,W49S20,694.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890792238829719070,...,1.0,6999.00,0.0,0.00,12.0,749.89,0.00,0.0,0.0,
154,01/12/2020,Sales,W49S20,695.0,9.199000e+11,Mr Tarun Varma,RH00745,NaN,NaN,890725301064518110,...,1.0,1350.00,0.0,0.00,18.0,205.93,0.00,0.0,0.0,
155,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,Q008210304,...,2.2,3505.00,0.4,0.00,5.0,166.89,0.00,0.0,0.0,
156,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,890511310051220020,...,1.0,2899.00,0.0,0.00,12.0,310.61,0.00,0.0,0.0,

In [24]:
dataset.reset_index(drop=True)

,Bill Date,Tran Type,Bill Prefix,Bill No,Customer Code,Customer Name,Sales Man Code,Item Promo Code,Bill Promo Code,StockNo,...,Qty,Value,Addons,Deduction,Tax Perc.,Tax,Item - Discount,Bill - Discount,Total - Discount,Old Bill Ref.
0,01/02/2020,Return,W49R19,4.0,9.198114e+11,Pradeep Sharma,RH07117,HO-30-W49-TRS-190120,NaN,890757867060919020,...,-1.0,(1959.00),0.0,(0.30),12.0,(209.93),(839.70),0.0,-839.7,W49S19-107
1,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792245642219090,...,1.0,2999.00,0.0,0.00,12.0,321.32,0.00,0.0,0.0,
2,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792161957619020,...,1.0,2799.00,0.0,0.00,12.0,299.89,0.00,0.0,0.0,
3,01/02/2020,Sales,W49S19,112.0,9.198101e+11,Mr. Vijay Gulati,RH07117,NaN,NaN,890792164244419100,...,1.0,2599.00,0.0,0.00,12.0,278.46,0.00,0.0,0.0,
4,01/02/2020,Sales,W49S19,113.0,9.198101e+11,Mrs. Shashi Mrs,RH06987,HO-30-TRS-270120,NaN,890766615475218080,...,1.0,1539.00,0.0,0.30,12.0,164.93,659.70,0.0,659.7,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,01/12/2020,Sales,W49S20,693.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890511344452420010,...,1.0,2399.00,0.0,0.00,12.0,257.04,0.00,0.0,0.0,
133,01/12/2020,Sales,W49S20,694.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890792238829719070,...,1.0,6999.00,0.0,0.00,12.0,749.89,0.00,0.0,0.0,
134,01/12/2020,Sales,W49S20,695.0,9.199000e+11,Mr Tarun Varma,RH00745,NaN,NaN,890725301064518110,...,1.0,1350.00,0.0,0.00,18.0,205.93,0.00,0.0,0.0,
135,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,Q008210304,...,2.2,3505.00,0.4,0.00,5.0,166.89,0.00,0.0,0.0,
136,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,890511310051220020,...,1.0,2899.00,0.0,0.00,12.0,310.61,0.00,0.0,0.0,

In [25]:
dataset.drop(columns=["Old Bill Ref."])

,Bill Date,Tran Type,Bill Prefix,Bill No,Customer Code,Customer Name,Sales Man Code,Item Promo Code,Bill Promo Code,StockNo,...,Doc Rate,Qty,Value,Addons,Deduction,Tax Perc.,Tax,Item - Discount,Bill - Discount,Total - Discount
0,01/02/2020,Return,W49R19,4.0,9.198114e+11,Pradeep Sharma,RH07117,HO-30-W49-TRS-190120,NaN,890757867060919020,...,2799.0,-1.0,(1959.00),0.0,(0.30),12.0,(209.93),(839.70),0.0,-839.7
2,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792245642219090,...,2999.0,1.0,2999.00,0.0,0.00,12.0,321.32,0.00,0.0,0.0
3,01/02/2020,Sales,W49S19,111.0,9.198101e+11,Mr. Vijay Gulati,RH07024,NaN,NaN,890792161957619020,...,2799.0,1.0,2799.00,0.0,0.00,12.0,299.89,0.00,0.0,0.0
4,01/02/2020,Sales,W49S19,112.0,9.198101e+11,Mr. Vijay Gulati,RH07117,NaN,NaN,890792164244419100,...,2599.0,1.0,2599.00,0.0,0.00,12.0,278.46,0.00,0.0,0.0
5,01/02/2020,Sales,W49S19,113.0,9.198101e+11,Mrs. Shashi Mrs,RH06987,HO-30-TRS-270120,NaN,890766615475218080,...,2199.0,1.0,1539.00,0.0,0.30,12.0,164.93,659.70,0.0,659.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,01/12/2020,Sales,W49S20,693.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890511344452420010,...,2399.0,1.0,2399.00,0.0,0.00,12.0,257.04,0.00,0.0,0.0
153,01/12/2020,Sales,W49S20,694.0,9.199716e+11,Surendra Aggarwal,RH00745,NaN,NaN,890792238829719070,...,6999.0,1.0,6999.00,0.0,0.00,12.0,749.89,0.00,0.0,0.0
154,01/12/2020,Sales,W49S20,695.0,9.199000e+11,Mr Tarun Varma,RH00745,NaN,NaN,890725301064518110,...,1350.0,1.0,1350.00,0.0,0.00,18.0,205.93,0.00,0.0,0.0
155,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,Q008210304,...,1593.0,2.2,3505.00,0.4,0.00,5.0,166.89,0.00,0.0,0.0
156,01/12/2020,Sales,W49S20,696.0,9.192127e+11,Mr Vibhor,RH00745,NaN,NaN,890511310051220020,...,2899.0,1.0,2899.00,0.0,0.00,12.0,310.61,0.00,0.0,0.0

In [26]:
dataset.to_csv("cleandata.csv")